# app/config/routing.yml
hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /connect

hwi_oauth_login:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix:   /login2
    
facebook_login:
    pattern: /login2/check-facebook

google_login:
    pattern: /login2/check-google

    
to_do_to_do:
    resource: "@ToDoToDoBundle/Resources/config/routing.yml"
    prefix:   /

#security_login_login:
#    resource: "@SecurityLoginLoginBundle/Resources/config/routing.yml"
#    prefix:   /

#app:
#    resource: @AppBundle/Controller/
#    type:     annotation
