security:
    encoders:
        #Symfony\Component\Security\Core\User\User: plaintext
        ToDo\Bundle\ToDoBundle\Entity\User: plaintext
          #algorithm:        sha1
          #encode_as_base64: false
          #iterations:       1


    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER, ROLE_OAUTH
        ROLE_OAUTH:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        administrators:
            entity: { class: ToDoToDoBundle:User, property: username }
        #in_memory:
        #    memory:
        #        users:
        #            user1:  { password: userpass1, roles: [ 'ROLE_USER' ] }
        #            user2:  { password: userpass2, roles: [ 'ROLE_USER' ] }
        #            admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }
        hwi_provider:
            id: to_do_to_do.oauth_user_provider

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        secured_area:
            pattern:    ^/
            anonymous:  ~
            oauth:
                resource_owners:
                    facebook:           "/login2/check-facebook"
                    google:             "/login2/check-google"

                login_path:        /login2
                use_forward:       false
                failure_path:      /login
                
                oauth_user_provider:                    
                    service: to_do_to_do.oauth_user_provider

           
            form_login:
                check_path: _login_check
                login_path: _login
                
                username_parameter:     _username
                password_parameter:     _password
                
                csrf_parameter:         _csrf_token
                intention:              authenticate
            logout:
                path:   _logout
                target: /
                
                
            #anonymous: ~
            #http_basic: ~

    access_control:
        # RESTRICTED PATHs
        - { path: ^/admin,    roles: ROLE_ADMIN }
        - { path: ^/user,    roles: ROLE_USER }
        - { path: ^/todoitems, roles: ROLE_USER }
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }

# app/config/security.yml



    access_control:
        