todoitems:
    path:     /
    defaults: { _controller: "ToDoToDoBundle:Todoitems:index" }

todoitems_show:
    path:     /{id}/show
    defaults: { _controller: "ToDoToDoBundle:Todoitems:show" }

todoitems_new:
    path:     /new
    defaults: { _controller: "ToDoToDoBundle:Todoitems:new" }

todoitems_create:
    path:     /create
    defaults: { _controller: "ToDoToDoBundle:Todoitems:create" }
    requirements: { _method: post }

todoitems_edit:
    path:     /{id}/edit
    defaults: { _controller: "ToDoToDoBundle:Todoitems:edit" }

todoitems_update:
    path:     /{id}/update
    defaults: { _controller: "ToDoToDoBundle:Todoitems:update" }
    requirements: { _method: post|put }

todoitems_delete:
    path:     /{id}/delete
    defaults: { _controller: "ToDoToDoBundle:Todoitems:delete" }
    requirements: { _method: post|delete }
